services:
  db-mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306
    networks:
      - docker-network
  board-back:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/board
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - db-mysql
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
